# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 17:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('countryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeteoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('wind', models.FloatField()),
                ('wind_dir', models.FloatField()),
                ('temp', models.FloatField()),
                ('relh', models.FloatField()),
                ('rain', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.IntegerField(primary_key=True, serialize=False)),
                ('stationname', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teledm.Country')),
            ],
        ),
        migrations.AddField(
            model_name='meteodata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teledm.Station'),
        ),
    ]
