# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='countryname',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='idx',
            new_name='idcountry',
        ),
        migrations.RenameField(
            model_name='meteodata',
            old_name='station',
            new_name='idstation',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='country',
            new_name='idcountry',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='stationid',
            new_name='idstation',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='stationname',
            new_name='station',
        ),
    ]
