# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160127_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteodata',
            old_name='idstation',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='idcountry',
            new_name='country',
        ),
    ]
