# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20160127_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteodata',
            old_name='station',
            new_name='station_id',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='country',
            new_name='country_id',
        ),
    ]
