"""
Django settings for crct project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fo9r1bxde8io8jz_9fr3*%93m3zf+p^)acos)9#@%(oe1+@a@z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django.contrib.gis',
    'django_ftpserver',
    'admin_reorder',
    'usermanagement',
    'bootstrap3',
    'bootstrap3_datetime',
    'djangojs',
    'wms',
    'sendfile',
#    'djng',
#    'highcharts',
#    'chartit',
#    'chart_tools',
#    'ncharts',
#    'ncdjango',
#    'tastypie',
#    'raster',
#    'djcelery',
    'leaflet',
    'djgeojson',
    'teledm',
    'portailCRCT'
]

LEAFLET_CONFIG = {
        'SPATIAL_EXTEND': [-15.0,0,57,52],
        'DEFAULT_CENTER': [20.0, 15.0],
        'DEFAULT_ZOOM': 4,
}
#RASTER_USE_CELERY = False
#RASTER_TILESIZE = 100

# SENDFILE settings
SENDFILE_BACKEND = 'sendfile.backends.development'
#SENDFILE_BACKEND = 'sendfile.backends.xsendfile'
#SENDFILE_BACKEND = 'sendfile.backends.nginx'
SENDFILE_ROOT = os.path.join(BASE_DIR, 'teledm/tmp')
SENDFILE_URL = '/teledm/tmp'

NC_SERVICE_DATA_ROOT = BASE_DIR+'/datas'
NC_TEMPORARY_FILE_LOCATION = BASE_DIR+'/tmp'


MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'crct.urls'
LOGIN_REDIRECT_URL = '/teledm/home'

ADMIN_REORDER = (
    'crct',
    {'app': 'teledm', 'models': ('teledm.Country','teledm.Station','teledm.MeteoData')},
    {'app': 'auth', 'models': ('auth.User',)},
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crct.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'web1',
        'USER': 'sebastien',
        'PASSWORD': 'emeraude',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}





SERIALIZATION_MODULES = {
    'geojson': 'djgeojson.serializers'
}

FTPSERVER_AUTHORIZER = 'django_ftpserver.authorizers.FTPAccountAuthorizer'
FTPSERVER_HANDLER = 'pyftpdlib.handlers.FTPHandler'
FTPSERVER_TLSHANDLER = 'pyftpdlib.handlers.TLS_FTPHandler'

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = BASE_DIR + "/teledm/static/"
STATIC_URL = '/static/'
